default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres_password
  host: localhost
  port: 5432

development:
  <<: *default
  database: marketplace_development

test:
  <<: *default
  database: marketplace_test

production:
  <<: *default
  database: marketplace_production
  password: <%= ENV["MARKETPLACE_DATABASE_PASSWORD"] %>
